apiVersion: v2
name: kegger
description: Helm Chart for Kegger https://github.com/elkrammer/kegger/
type: application
version: 0.0.4
appVersion: "0.0.1"
dependencies:
  - name: postgresql
    version: "10.3.*"
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
