version: '3'

services:
  api:
    build: ./api
    restart: always
    ports:
      - "4040:4040"
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_USERNAME: $DB_USERNAME
      JWT_SECRET: $JWT_SECRET
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      RUN_MIGRATIONS: "false"
    depends_on:
      - "db"
      - "migrate"
    volumes:
      - "./.env:/app/.env"

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_SERVER: $VUE_APP_API_SERVER
        VUE_APP_EMAIL_FROM_NAME: $VUE_APP_EMAIL_FROM_NAME
        VUE_APP_EMAIL_FROM: $VUE_APP_EMAIL_FROM
        VUE_APP_EMAIL_SUBJECT: $VUE_EMAIL_SUBJECT
        VUE_APP_EMAIL_TO: $VUE_APP_EMAIL_TO
        VUE_APP_EMAIL_TO_NAME: $VUE_APP_EMAIL_TO_NAME
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

  db:
    image: postgres:12.1-alpine
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database",  "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable", "up"]
    depends_on:
      - "db"
    volumes:
      - ./api/db/migrations:/migrations

volumes:
  db_data:
    driver: local
