apiVersion: v1
kind: Secret
metadata:
  name: kegger
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.jwtSecret }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- if .Values.sendgridApiKey }}
  sendgrid-api-key: {{ .Values.sendgridApiKey | b64enc | quote }}
  {{- else }}
  sendgrid-api-key:
  {{- end }}
