name: build-and-push

on:
  push:
    branches:
      - 'master'

jobs:
  build-push:
    env:
        IMAGE: elkrammer/kegger
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

    # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish API image with tag
      uses: docker/build-push-action@v2
      with:
          context: ./api
          file: api/Dockerfile
          push: true
          tags: |
            frontend:${{ steps.prep.outputs.BUILD_ID }}
    - name: Build and publish FrontEnd image with tag
      uses: docker/build-push-action@v2
      with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: |
            backend:${{ steps.prep.outputs.BUILD_ID }}
